# Generated by Django 5.0.2 on 2024-02-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='number',
            field=models.IntegerField(blank=True, default=0, help_text='Phone number'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='other_problems',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
