# Generated by Django 5.0.2 on 2024-02-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_alter_hackathon_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='healthcare_problems',
            new_name='healthcare_problem',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='supported_ages',
            field=models.CharField(choices=[('<20s', '<20s'), ('20s', '20s'), ("30's", "30's"), ("40's", "40's"), ("50's", "50's"), (">60's", ">60's")], max_length=255),
        ),
    ]
