# Generated by Django 5.0.2 on 2024-02-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_rename_healthcare_problems_hackathon_healthcare_problem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primaryskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hackathon',
            name='skill',
            field=models.ManyToManyField(to='hackathon.primaryskill'),
        ),
    ]
