# Generated by Django 5.0.2 on 2024-02-16 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_primaryskill_hackathon_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
