# Generated by Django 5.0.2 on 2024-02-16 19:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_hackathon_created_hackathon_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='other_problems',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='other_problems'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='overview', max_length=5000),
        ),
    ]
