# Generated by Django 5.0.2 on 2024-02-19 06:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_alter_hackathon_other_problems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='other_problems',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000),
        ),
    ]
